from ap1200 import NetworkInterface

print("AP1200 Grouped TX Demo")
print("Homepage: https://github.com/lavajuno/ap1200/")
print("Updates: https://github.com/lavajuno/ap1200/releases")
print("Enter source callsign/ID")
source_id = input(":")
print("Enter source port (0-255)")
port = int(input(":"))
ni = NetworkInterface(source_id, port)
while True:
    print("Enter message string (ASCII):")
    user_message = input()
    print("Enter dest callsign/ID")
    dest_id = input(":")
    encoded_message = user_message.encode("ascii", "ignore")
    print("Transmitting...")
    p = ni.make_packet(dest_id, encoded_message)
    gp = ni.make_packet(dest_id, p.save() + p.save())
    gp.set_group_flag(True)
    ni.send_packet(gp)
    print("Done. (CTRL-C to exit)\n")
